# Generated by Django 5.2.7 on 2025-10-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cartela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível na coordenação'), ('DISTRIBUIDA', 'Distribuída para movimento'), ('VENDIDA', 'Vendida (aguardando acerto)'), ('ACERTADA', 'Acertada (pagamento confirmado)')], default='DISPONIVEL', max_length=12)),
                ('data_distribuicao', models.DateField(blank=True, null=True)),
                ('data_acerto', models.DateField(blank=True, null=True)),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimento')),
            ],
        ),
    ]
