# Generated by Django 5.2.7 on 2025-10-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartela',
            name='cortesia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartela',
            name='devolvida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PREFEITURA', 'Prefeitura'), ('DESCONTO_SERVICO', 'Desconto em Serviços')], max_length=17)),
                ('membro_pastoral', models.CharField(blank=True, default='', max_length=100)),
                ('obs', models.TextField(blank=True, default='', max_length=200)),
                ('cartelas_cortesia', models.ManyToManyField(related_name='acertos_cortesia', to='core.cartela')),
                ('cartelas_devolvidas', models.ManyToManyField(related_name='acertos_devolvidas', to='core.cartela')),
                ('cartelas_vendidas', models.ManyToManyField(related_name='acertos_vendidas', to='core.cartela')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.movimento')),
            ],
        ),
    ]
