# Generated by Django 5.2.7 on 2025-10-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartela_cortesia_cartela_devolvida_acerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acerto',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='cartela',
            name='cortesia',
        ),
        migrations.RemoveField(
            model_name='cartela',
            name='devolvida',
        ),
        migrations.AddField(
            model_name='acerto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acerto',
            name='cartelas_cortesia',
            field=models.ManyToManyField(blank=True, related_name='acertos_cortesia', to='core.cartela'),
        ),
        migrations.AlterField(
            model_name='acerto',
            name='cartelas_devolvidas',
            field=models.ManyToManyField(related_name='acertos_devolucao', to='core.cartela'),
        ),
        migrations.AlterField(
            model_name='acerto',
            name='cartelas_vendidas',
            field=models.ManyToManyField(related_name='acertos_venda', to='core.cartela'),
        ),
        migrations.AlterField(
            model_name='acerto',
            name='membro_pastoral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acertado por'),
        ),
        migrations.AlterField(
            model_name='acerto',
            name='tipo_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PREFEITURA', 'Prefeitura'), ('DESCONTO_SERVICO', 'Desconto em Serviços')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartela',
            name='movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelas', to='core.movimento'),
        ),
        migrations.AlterField(
            model_name='cartela',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('DISTRIBUIDA', 'Distribuída'), ('ACERTADA', 'Acertada'), ('DEVOLVIDA', 'Devolvida'), ('CORTESIA', 'Cortesia')], default='DISPONIVEL', max_length=12),
        ),
    ]
