# Generated by Django 5.2.7 on 2025-10-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_acerto_obs_remove_cartela_cortesia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acerto',
            name='movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acertos', to='core.movimento'),
        ),
    ]
