# Generated by Django 5.2.7 on 2025-10-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_acerto_movimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_distribuicao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('cartelas', models.ManyToManyField(related_name='distribuicoes', to='core.cartela')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='core.movimento')),
            ],
        ),
    ]
