# Generated by Django 5.2.7 on 2025-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_distribuicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acerto',
            name='cartelas_cortesia',
        ),
        migrations.RemoveField(
            model_name='acerto',
            name='cartelas_devolvidas',
        ),
        migrations.RemoveField(
            model_name='acerto',
            name='cartelas_vendidas',
        ),
        migrations.AddField(
            model_name='acerto',
            name='quantidade_cortesia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acerto',
            name='quantidade_devolvidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acerto',
            name='quantidade_vendidas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
