# Generated by Django 5.2.7 on 2025-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_acerto_cartelas_cortesia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acerto',
            name='quantidade_cortesia',
        ),
        migrations.RemoveField(
            model_name='acerto',
            name='quantidade_devolvidas',
        ),
        migrations.RemoveField(
            model_name='acerto',
            name='quantidade_vendidas',
        ),
        migrations.AddField(
            model_name='acerto',
            name='cartelas_cortesia',
            field=models.ManyToManyField(blank=True, related_name='acerto_cortesia', to='core.cartela'),
        ),
        migrations.AddField(
            model_name='acerto',
            name='cartelas_devolvidas',
            field=models.ManyToManyField(blank=True, related_name='acerto_devolucao', to='core.cartela'),
        ),
        migrations.AddField(
            model_name='acerto',
            name='cartelas_vendidas',
            field=models.ManyToManyField(blank=True, related_name='acerto_venda', to='core.cartela'),
        ),
    ]
