# Generated by Django 5.2.7 on 2025-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_acerto_quantidade_cortesia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='membro_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Membro Responsável'),
        ),
    ]
