# Generated by Django 5.2.7 on 2025-10-31 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_distribuicao_membro_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartela',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('DISTRIBUIDA', 'Distribuída'), ('ACERTADA', 'Acertada'), ('DEVOLVIDA', 'Devolvida'), ('CORTESIA', 'Cortesia'), ('CANCELADA', 'Cancelada')], default='DISPONIVEL', max_length=12),
        ),
        migrations.CreateModel(
            name='LogCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo do Cancelamento')),
                ('data_cancelamento', models.DateTimeField(auto_now_add=True)),
                ('cartela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_cancelamento', to='core.cartela')),
            ],
        ),
    ]
