# Generated by Django 5.2.7 on 2025-11-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cartela_status_logcancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcancelamento',
            name='movimento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimento'),
        ),
        migrations.AddField(
            model_name='logcancelamento',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
